articles/urls.py
from django.urls import path
from .import views

app_name ="articles"
urlpatterns = [
    # 1:classbaseview
    # path("",views.ArticleListVuew.as_view(),name="articles"),
    # path('<int:pk>/',views.BlogDetailview.as_view(),name = "detail"),
    # path('edite/<int:pk>/',views.ArticlesUpdateView.as_view(),name= "update"),
    # path('delete/<int:pk>/',views.ArticlesDeleteView.as_view(),name= "delete"),
    # path('new/',views.CreatViews.as_view(),name ='newpost'),
  

    # 2:function
    path('delete/<int:pk>/',views.articledelet,name= "delete"),
    path('<int:pk>/edit/',views.ArticleUpdate,name= "update"),
    path('<int:pk>/',views.article_detail,name = "detail"),
    path('new/',views.articlecreate,name ='newpost'),
    path("",views.articlelist,name="articles"),

]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('articles/',include('articles.urls')),
    # path('',TemplateView.as_view(template_name ="home.html"),name="home"),
    path('',include('pages.urls')),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("articles:detail",kwargs={"pk":self.id})
        # return reverse("articles:article_detail",args=[str(self.id)])



class Comment(models.Model):
    article = models.ForeignKey(Article,related_name="comments",on_delete=models.CASCADE)
    comment = models.TextField()
    writer  = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

    def __str__(self):
        return str(self.writer)+" "+str(self.id)
    

    def get_absolute_url(self):
        return reverse("articles:articles")

articles/forms.py
from django import forms
from .models import Comment,Article

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)
        # widgets ={
        #     "article":forms.HiddenInput(),
        #     "writer":forms.HiddenInput(),
        # }
# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = [
#             "writer",
#             "comment",
#             "article"
#         ] 


class ArticleForm(forms.ModelForm):
    class Meta:
        model =Article
        fields = ("title","body")
        

articles/views.py
from typing import Any, Dict, Optional
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponseForbidden
from django.views.generic import ListView
from .models import Article
from django.views.generic.edit import FormMixin
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView,DeleteView,CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (LoginRequiredMixin,
UserPassesTestMixin)
from .forms import CommentForm,ArticleForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

# 1:classbaseview
# class ArticleListVuew(ListView):
#     model = Article
#     template_name = "articles/article_list.html"

# 2:function
def articlelist(request): 
    article = Article.objects.all()
    context = {
        "article":article
    }
    return render(request,"articles/article_list.html",context)




# 1:classbaseview
# class BlogDetailview(FormMixin,DetailView):
#     model = Article
#     template_name = "articles/detailview.html"
#     form_class = CommentForm

#   1:classbaseview (detail)     
    # def get_success_url(self):
    #    return reverse("articles:detail",kwargs={"pk":self.object.id})
    # def get_context_data(self, **kwargs):
    #     context = super(BlogDetailview,self).get_context_data(**kwargs)
    #     context['form'] = CommentForm(initial={"article":self.object ,"writer":self.request.user})
    #     return context 
    # def post(self,*args,**kwargs):
    #     self.object = self.get_object()
    #     form = self.get_form()
    #     if form.is_valid():
    #         return self.form_valid(form)
    #     else:
    #         pass
    # def form_valid(self, form):
    #     form.save() 
    #     return super(BlogDetailview,self).form_valid(form)
      




# 2:function
def article_detail(request,pk):
    # article = Article.objects.get(id=pk)
    article = get_object_or_404(Article,id=pk)
    form = CommentForm()
    if request.user.is_authenticated:
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.writer  = request.user   
                obj.article = article
                obj.save()
                return HttpResponseRedirect(request.path_info)
        else:
            form = CommentForm()
    else:
        article = get_object_or_404(Article,id=pk)
        return render(request,"articles/detailview.html",{"article":article})
    
    return render(request,"articles/detailview.html",{"article":article ,"form":form})
 




# 1:classbaseview
# class ArticlesUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    # model = Article
    # fields = ('title',"body")
    # template_name = "articles/update.html"

    # def test_func(self):
    #     object = self.get_object()
    #     return object.author == self.request.user




# 2:function
@login_required
def ArticleUpdate(request,pk):
    article =get_object_or_404(Article,id=pk)
    if request.user == article.author:
        form = ArticleForm(request.POST or None , instance=article)
        if request.method == "POST":
            if form.is_valid():
                form.save()
                return 
        
        form = ArticleForm
        return render(request,"articles/update.html",{"form":form})
    else:
        return HttpResponseForbidden()






# 1:classbaseview
# class ArticlesDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    # model = Article
    # template_name = "articles/delete.html"
    # success_url = reverse_lazy('articles:articles')

    # def test_func(self):
        # object = self.get_object()
        # return object.author == self.request.user



# 2:function
@login_required
def articledelet(request,pk):
    article = get_object_or_404(Article,id=pk)
    if request.user == article.author:
        if request.method == "POST":
            article.delete()
            return HttpResponseRedirect("/"+"articles/")
        return render(request,"articles/delete.html",{"article":article})
    else:
        return HttpResponseForbidden()


# 1:classbaseview
# class CreatViews(LoginRequiredMixin,CreateView):
    # model = Article
    # template_name = "articles/creatview.html"
    # fields = ("title","body")
    # def form_valid(self,form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)
    




# 2:function
@login_required
def articlecreate(request):
    # if request.user.is_authenticated:
        form = ArticleForm()
        if request.method == "POST":
            form = ArticleForm(request.POST)
            if form.is_valid():
                post_title = form.cleaned_data["title"]
                post_body = form.cleaned_data["body"]
                post_author =request.user
                object = Article(title=post_title,body=post_body,author=post_author)
                object.save()
                return HttpResponseRedirect("/"+"articles/")
        else:
            form= ArticleForm()  
    # else:
    #     return HttpResponseRedirect("/"+"accounts/login/")

        return render(request,"articles/creatview.html",{"form":form})
    

templates/articles/article_list.html
{% extends 'base.html' %}


{% block title %}
articles
{% endblock %}

{% block content %}
<h1> Articles </h1>
<hr>
 <ul>
    {% for Article in article %}
    <li>
       <a href="{{Article.get_absolute_url}}">{{Article.title}}</a>
        <br>
        {% if user.is_authenticated  and Article.author == user %} 
        <a href="{% url 'articles:update' Article.id %}">update</a> | <a href="{% url 'articles:delete' Article.id %}">Delete</a>
        {% endif %}
        <hr>
    </li>
    {% endfor %}
 </ul>
{% endblock %}

templates/articles/creatview.html
{% extends 'base.html' %}

{% block title %}
new post
{% endblock title %}


{% block content %}
<h1>Creat Post</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">New</button>
</form>

{% endblock %}

templates/articles/delete.html
{% extends 'base.html' %}

{% block title %}
Delete
{% endblock title %}


{% block content %}
<h1>Delete {{article}}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>are you sure to delete{{Article.title}}?</p>
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

{% endblock %}

templates/articles/detailview.html
{% extends 'base.html' %}



{% block content %}
<h3>detail of {{article.title}}</h3>
<hr>
<h5>by {{article.author}} ot {{article.date}}</h5>
<p> {{article.body}}</p>
<hr>
<ul>
    {% for comment in article.comments.all%}
    <li>
        <b>{{comment.writer}}</b>| {{comment.comment}}
    </li>
    {% endfor %}
</ul>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Comment">
</form>

<a href="{% url 'articles:articles' %}">>>list bloge<<</list></a>
{% endblock %}

templates/articles/update.html
{% extends 'base.html' %}

{% block title %}
update
{% endblock title %}


{% block content %}
<h1>edit {{object}}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock %}