articles/urls.py
from django.urls import path
from .import views

app_name ="articles"
urlpatterns = [
    # 1:classbaseview
    # path("",views.ArticleListVuew.as_view(),name="articles"),
    # path('<int:pk>/',views.BlogDetailview.as_view(),name = "detail"),
    # path('edite/<int:pk>/',views.ArticlesUpdateView.as_view(),name= "update"),
    # path('delete/<int:pk>/',views.ArticlesDeleteView.as_view(),name= "delete"),
    # path('new/',views.CreatViews.as_view(),name ='newpost'),
  

    # 2:function
    path('delete/<int:pk>/',views.articledelet,name= "delete"),
    path('<int:pk>/edit/',views.ArticleUpdate,name= "update"),
    path('<int:pk>/',views.article_detail,name = "detail"),
    path('new/',views.articlecreate,name ='newpost'),
    path("",views.articlelist,name="articles"),

]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('articles/',include('articles.urls')),
    # path('',TemplateView.as_view(template_name ="home.html"),name="home"),
    path('',include('pages.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block heder %}
  
  {% endblock heder %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        new app
        {% endblock title %}
        
    </title>
</head>
<body>
    <header>
        <!-- {% if user.is_authenticated %}
        Hi{{user.username}}
        <p><a href="{% url 'logout' %}">Logout</a></p>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'signup' %}">Register</a>
        {% endif %} -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">Home</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %} 
                    <li>
                        <a class="nav-link disabled" aria-disabled="true">Hi^-^{{user}}</a>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">logout</a>
                  </li>
                  <li>
                    <a href="{% url 'articles:newpost' %}" class="nav-link active" aria-disabled="page">New +</a>
                </li>

                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'login' %}">login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Register</a>
                  </li>
                  {%endif%}
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true"></a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>
    {% block content %}

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block title %}
Home Page

{% endblock title %}



{% block content %}
<h1>
    Home Page
</h1>

<hr>

<p>
welcome too my bloge
</p>
{% endblock content %}